### ISSUE TITLE
FX Explorer Breakout Board

### ISSUE THREAD

**Issue by patricknoack** [analogdevicesinc/iSensor-FX3-API#10]
Hello Juan,

I would like to source the FX Explorer Breakout Board as a single piece. 

We have a 
* ADcmXL1021-1 Module
* ADCMXL_BRKOUT/PCBZ Breakout Board
and want to order
* Cypress Semiconductor EZ-USB FX3 Board (CYUSB3KIT-003)

but miss the breakout board...

Any suggestions?

BR
Patrick

**Comment by ajn96** [comment]
Hello Patrick,

At present, I don't think there is any way to order the FX3 breakout board as a standalone piece. It can be purchased, but only as part of the ADcmXL evaluation kit (which includes DUT, both breakout boards, FX3, cables, etc).

If you want to get one of the breakout boards manufactured, the schematic, layout, gerbers, etc are available [here](https://github.com/analogdevicesinc/iSensor-FX3-API/tree/master/hardware/Cypress%20FX3%20Explorer%20Eval%20Breakout%20Board)

Another option would be the new EVAL-ADIS-FX3 board. This board is fully compatible with the ADCMXL breakout, with no extra adapters required. This board would also save you from having to purchase the Cypress FX3 eval board.
https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/eval-adis-fx3.html

I will double check with my colleague who maintains the ADcmXL eval software that the new EVAL-ADIS-FX3 board is supported. An update to the resource files packaged with the GUI might be required.

**Comment by patricknoack** [comment]
Hello Alex,
it feels great to hear from somebody after all this time who helps to pave a road towards a solution.  
Just to be on the safe side: we have a ADCMXL1021: this unit will be compatible with the new EVAL-ADIS-FX3 board allowing to extract the FFT calculated on the device?  
Is the board already available? I could not spot a price when asking Google.

BR
Patrick

**Comment by ajn96** [comment]
Hello Patrick,

The EVAL-ADIS-FX3 can be purchased from ADI directly ($175) or Digikey, although it is currently out of stock there.

Right now you can use the ADcmXL with the iSensor IMU Eval GUI ([wiki](https://wiki.analog.com/resources/eval/user-guides/inertial-mems/evaluation-systems/eval-adis-fx3-eval-user-guide)) ([GitHub](https://github.com/analogdevicesinc/iSensor-FX3-Eval))

This GUI will allow you to configure the ADcmXL and log FFT data, although it does not have the nice FFT plotting window the ADcmXL eval GUI does.

The FX3 API also presents a simplified interface to Matlab/Python/Labview through .NET interop, so if you wanted, you can write your own data analysis scripts using this board. See: https://github.com/analogdevicesinc/iSensor-FX3-API/tree/master/src_wrapper

I also checked with my colleague, and the FX3 firmware packaged with the ADcmXL eval GUI will have to be updated to support the EVAL-ADIS-FX3. I will post an update here whenever that is released.

-Alex

**Comment by patricknoack** [comment]
Hello Alex,

so I understand that you would suggest to wait until the new firmware for the ADcmXL supporting the  EVAL-ADIS-FX3 is released and to order the board then. Does it make any sense to order the board now as delivery time seems to be 8 weeks atm, hoping that the firmware has been released by the time of delivery?

Best
Patrick

**Comment by ajn96** [comment]
Hello Patrick,

Sorry for the confusion! The update I was referring to is a change to the FX3 firmware packaged with the [ADcmXL evaluation GUI](https://wiki.analog.com/resources/eval/user-guides/inertial-mems/imu/adcmxl-pc-eval). The current FX3 firmware packaged with the ADcmXL GUI supports the cypress board w/breakout, but not the EVAL-ADIS-FX3. No change is required for the ADcmXL3021 itself, and the EVAL-ADIS-FX3 will be able to load the new firmware without user intervention once the GUI is updated.

It should be safe to order an EVAL-ADIS-FX3 now. I spoke to my colleague about it, and while can't say definitively, I strongly suspect the update to the ADcmXL GUI will take less than 8 weeks.

Thanks,
Alex

**Comment by patricknoack** [comment]
Hello Alex,

great feedback, thank you! 

So, once the Eval GUI has been adapted to the EVAL-ADIS-FX3 I could use the sensor without any additional hardware with the Eval GUI and the .NET interface? In this case I would order the EVAL-ADIS-FX3 straight away.  

Just to be on the safe side:

- This solution will also work with the ADcmXL1021 which we actually have (1 axis only)?
- Any additional cables need to attach ADcmXL1021  to EVAL-ADIS-FX3 ?

BR
Patrick

**Comment by ajn96** [comment]
Hello Patrick,

The EVAL-ADIS-FX3 includes the controller board, USB cable, and 16-pin DUT connection cable. This cable plugs directly into the ADCMXL_BRKOUT/PCBZ, which in turn connects to the ADcmXL3021 or 1021. So you should be able to use it out of the box with the existing iSensor Eval GUI, and the ADcmXL Eval GUI (pending update to the GUI).

The ADcmXL1021 and ADcmXL3021 are pin compatible and register interface compatible (outside of some small changes to the real time stream format). So any setup for the 3021 should generally work for the 1021. The iSensor Eval GUI supports both parts in the device selection drop down (see [guide](https://wiki.analog.com/resources/eval/user-guides/inertial-mems/evaluation-systems/eval-adis-fx3)). You should not need any additional cables, since you already have the ADCMXL_BRKOUT/PCBZ.

Thanks,
Alex

**Comment by ajn96** [comment]
The ADcmXL GUI has been updated on the wiki page to the latest FX3 API revision.
https://wiki.analog.com/resources/eval/user-guides/inertial-mems/imu/adcmxl-pc-eval?rev=1618864990
