### ISSUE TITLE
Add relative directory support to Python wrapper example

### ISSUE THREAD

**Issue by ajn96** [analogdevicesinc/iSensor-FX3-API#7]
Currently, resource paths are hard coded. Ideally, should work out of the box, without needing to adjust any code

**Comment by ajn96** [comment]
Pythonnet just added support for Python 3.9
https://github.com/pythonnet/pythonnet/releases/tag/v2.5.2

I hadn't wanted to deal with installing multiple Python versions. Will deal with this feature soon

**Comment by juchong** [comment]
I recommend using this to manage multiple Python versions. https://scoop.sh/

**Comment by ajn96** [comment]
https://github.com/analogdevicesinc/iSensor-FX3-API/commit/38201909f37dd9141e2160d60844a6c902bd4916

Done
